### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by luthfianto** [adamdbradley/ionic-angular2#1]
I'm on Windows and io.js v1.4.3.

Installed node-sass and still got an error

```
gulp build
D:\ionic-angular2\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass
          ^
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (D:\ionic-angular2\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (D:\ionic-angular2\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Module.require (module.js:349:17)
    at require (module.js:368:17)
    at Object.<anonymous> (D:\ionic-angular2\node_modules\gulp-sass\index.js:3:17)
    at Module._compile (module.js:444:26)
```

**Comment by oliversalzburg** [comment]
@rilut This might help: http://stackoverflow.com/questions/28409100/try-reinstalling-node-sass-on-node-0-12

**Comment by luthfianto** [comment]
```
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/win32-x64-node-1.4/binding.node

> node-sass@2.1.1 postinstall D:\ionic-angular2\node_modules\gulp-sass\node_modules\node-sass
> node scripts/build.js

gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (D:\ionic-angular2\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\lib\configure.js:109:14)
gyp ERR! stack     at D:\ionic-angular2\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\lib\configure.js:98:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:707:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at maybeClose (child_process.js:984:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1153:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:166:7)
gyp ERR! stack     at Pipe.close (net.js:464:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "D:\\ionic-angular2\\node_modules\\gulp-sass\\node_modules\\node-sass\\node_modules\\pangyp\\bin\\node-gyp" "rebuild"
gyp ERR! cwd D:\ionic-angular2\node_modules\gulp-sass\node_modules\node-sass
gyp ERR! node -v v1.4.3
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
Build failed
```

Seems I have two issues here: dead node-sass-binaries link and python version (which I can solve. Idk about the node-sass-binaries)

**Comment by luthfianto** [comment]
Oh it seems I need to downgrade the io.js (https://github.com/sass/node-sass/issues/699)

Maybe I'll just wait until node-sass-binaries support io.js 1.4+
